app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: Flint
publisher_url: https://github.com/zen3dmed-wq/F-Windows
display_name: Flint
create_desktop_icon: true
install_dir_name: "{autopf64}\\Flint"
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - es
  - fr
  - pt
  - ru
  - tr
script_template: inno_setup.sas
